name: Deploy App Render Container
  uses: gh-actions-workflows/deploy-docker-render@v1.1
  with:
    deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
    image-url: ahmed5827/simplewebprod:latest
    render-api-key: ${{ secrets.RENDER_API_KEY }}
    wait-for-deployment: true

